### ISSUE TITLE
convert mBuffer array to vector

### ISSUE THREAD

**Issue by hmoffatt** [kusharami/qzstream#1]
MSVC complains about the mBuffer member being quite large for the stack - 32k. Also it's a C array and this is C++.

I suggest converting it to a std::vector or QVector.

**Comment by kusharami** [comment]
Thanks for suggestion. You may create a pull request if you want, because I don't know exactly when I'll make this fix.

**Comment by kusharami** [comment]
Fixed this issue

**Comment by hmoffatt** [comment]
Thanks for these fixes
